package ch.chrigu.wotr.gamestate

import ch.chrigu.wotr.figure.Figure
import ch.chrigu.wotr.figure.FigureType
import ch.chrigu.wotr.figure.Figures
import ch.chrigu.wotr.figure.FiguresType
import ch.chrigu.wotr.location.Location
import ch.chrigu.wotr.location.LocationName
import ch.chrigu.wotr.location.LocationName.*
import ch.chrigu.wotr.location.LocationType
import ch.chrigu.wotr.location.LocationType.*
import ch.chrigu.wotr.nation.NationName
import ch.chrigu.wotr.nation.NationName.*

object GameStateFactory {

    private val initFigures = mapOf(
        f(ERED_LUIN, 1, 0, 0),
        f(EREBOR, 1, 2, 1),
        f(IRON_HILLS, 1, 0, 0),
        f(THE_SHIRE, 1, 0, 0),
        f(NORTH_DOWNS, 0, 1, 0),
        f(DALE, 1, 0, 1),
        f(CARROCK, 1, 0, 0),
        f(BREE, 1, 0, 0),
        f(GREY_HAVENS, 1, 1, 1),
        f(RIVENDELL, 0, 2, 1),
        f(WOODLAND_REALM, 1, 1, 1),
        f(LORIEN, 1, 2, 1),
        f(EDORAS, 1, 1, 0),
        f(FORDS_OF_ISEN, 2, 0, 1),
        f(HELMS_DEEP, 1, 0, 0),
        f(MINAS_TIRITH, 3, 1, 1),
        f(DOL_AMROTH, 3, 0, 0),
        f(OSGILIATH, 2, 0, 0, GONDOR),
        f(PELARGIR, 1, 0, 0),
        f(ORTHANC, 4, 1, 0),
        f(NORTH_DUNLAND, 1, 0, 0),
        f(SOUTH_DUNLAND, 1, 0, 0),
        f(FAR_HARAD, 3, 1, 0),
        f(NEAR_HARAD, 3, 1, 0),
        f(NORTH_RHUN, 2, 0, 0),
        f(SOUTH_RHUN, 3, 1, 0),
        f(UMBAR, 3, 0, 0),
        f(BARAD_DUR, 4, 1, 1),
        f(DOL_GULDUR, 5, 1, 1),
        f(GORGOROTH, 3, 0, 0),
        f(MINAS_MORGUL, 5, 0, 1),
        f(MORIA, 2, 0, 0),
        f(MOUNT_GUNDABAD, 2, 0, 0),
        f(NURN, 2, 0, 0),
        f(MORANNON, 5, 0, 1)
    )

    private val initLocations = listOf(
        l(FORLINDON, listOf(NORTH_ERED_LUIN, ERED_LUIN, GREY_HAVENS)),
        l(NORTH_ERED_LUIN, listOf(FORLINDON, ERED_LUIN, EVENDIM), DWARVES),
        l(ERED_LUIN, listOf(FORLINDON, GREY_HAVENS, TOWER_HILLS, NORTH_ERED_LUIN, EVENDIM), DWARVES, VILLAGE),
        l(EVENDIM, listOf(NORTH_ERED_LUIN, ERED_LUIN, TOWER_HILLS, THE_SHIRE, BUCKLAND, NORTH_DOWNS, ARNOR)),
        l(ARNOR, listOf(EVENDIM, NORTH_DOWNS, ETTENMOORS, ANGMAR)),
        l(ANGMAR, listOf(ARNOR, ETTENMOORS, MOUNT_GRAM), SAURON, CITY),
        l(MOUNT_GRAM, listOf(ANGMAR, ETTENMOORS, MOUNT_GUNDABAD), SAURON),
        l(MOUNT_GUNDABAD, listOf(MOUNT_GRAM, EAGLES_EYRIE), SAURON, STRONGHOLD),
        l(CARROCK, listOf(EAGLES_EYRIE, OLD_FORD, RHOSGOBEL, OLD_FOREST_ROAD, WESTERN_MIRKWOOD, NORTHERN_MIRKWOOD), NORTHMEN, VILLAGE),
        l(NORTHERN_MIRKWOOD, listOf(CARROCK, WESTERN_MIRKWOOD, WOODLAND_REALM, WITHERED_HEATH)),
        l(WITHERED_HEATH, listOf(NORTHERN_MIRKWOOD, WOODLAND_REALM, DALE, EREBOR)),
        l(EREBOR, listOf(WITHERED_HEATH, DALE, IRON_HILLS), DWARVES, STRONGHOLD),
        l(IRON_HILLS, listOf(EREBOR, DALE, VALE_OF_THE_CARNEN, EAST_RHUN), DWARVES, VILLAGE),
        l(GREY_HAVENS, listOf(FORLINDON, HARLINDON, TOWER_HILLS, ERED_LUIN), ELVES, STRONGHOLD),
        l(TOWER_HILLS, listOf(GREY_HAVENS, SOUTH_ERED_LUIN, THE_SHIRE, EVENDIM, ERED_LUIN)),
        l(THE_SHIRE, listOf(TOWER_HILLS, SOUTH_ERED_LUIN, OLD_FOREST, BUCKLAND, EVENDIM), NORTHMEN, CITY),
        l(BUCKLAND, listOf(THE_SHIRE, OLD_FOREST, CARDOLAN, SOUTH_DOWNS, BREE, NORTH_DOWNS, EVENDIM), NORTHMEN),
        l(BREE, listOf(NORTH_DOWNS, BUCKLAND, SOUTH_DOWNS, WEATHER_HILLS), NORTHMEN, VILLAGE),
        l(NORTH_DOWNS, listOf(ARNOR, EVENDIM, BUCKLAND, BREE, WEATHER_HILLS, ETTENMOORS), NORTHMEN),
        l(ETTENMOORS, listOf(ANGMAR, ARNOR, NORTH_DOWNS, WEATHER_HILLS, TROLLSHAWS, MOUNT_GRAM)),
        l(WEATHER_HILLS, listOf(ETTENMOORS, NORTH_DOWNS, BREE, SOUTH_DOWNS, TROLLSHAWS)),
        l(TROLLSHAWS, listOf(ETTENMOORS, WEATHER_HILLS, SOUTH_DOWNS, HOLLIN, FORDS_OF_BRUINEN, RIVENDELL)),
        l(RIVENDELL, listOf(TROLLSHAWS, FORDS_OF_BRUINEN), ELVES, STRONGHOLD),
        l(FORDS_OF_BRUINEN, listOf(RIVENDELL, TROLLSHAWS, HOLLIN, HIGH_PASS)),
        l(HIGH_PASS, listOf(FORDS_OF_BRUINEN, GOBLINS_GATE)),
        l(GOBLINS_GATE, listOf(HIGH_PASS, OLD_FORD)),
        l(OLD_FORD, listOf(EAGLES_EYRIE, GOBLINS_GATE, GLADDEN_FIELDS, RHOSGOBEL, CARROCK)),
        l(EAGLES_EYRIE, listOf(MOUNT_GUNDABAD, OLD_FORD, CARROCK)),
        l(RHOSGOBEL, listOf(CARROCK, OLD_FORD, GLADDEN_FIELDS, NORTH_ANDUIN_VALE, NARROWS_OF_THE_FOREST, OLD_FOREST_ROAD), NORTHMEN),
        l(WESTERN_MIRKWOOD, listOf(NORTHERN_MIRKWOOD, CARROCK, OLD_FOREST_ROAD, WOODLAND_REALM)),
        l(WOODLAND_REALM, listOf(NORTHERN_MIRKWOOD, WESTERN_MIRKWOOD, OLD_FOREST_ROAD, DALE, WITHERED_HEATH), ELVES, STRONGHOLD),
        l(OLD_FOREST_ROAD, listOf(WOODLAND_REALM, WESTERN_MIRKWOOD, CARROCK, RHOSGOBEL, NARROWS_OF_THE_FOREST, EASTERN_MIRKWOOD, NORTHERN_RHOVANION, DALE), NORTHMEN),
        l(DALE, listOf(EREBOR, WITHERED_HEATH, WOODLAND_REALM, OLD_FOREST_ROAD, NORTHERN_RHOVANION, VALE_OF_THE_CARNEN, IRON_HILLS), NORTHMEN, CITY),
        l(VALE_OF_THE_CARNEN, listOf(IRON_HILLS, DALE, NORTHERN_RHOVANION, VALE_OF_THE_CELDUIN, NORTH_RHUN, EAST_RHUN)),
        l(EAST_RHUN, listOf(IRON_HILLS, VALE_OF_THE_CARNEN, NORTH_RHUN, SOUTH_RHUN), SOUTHRONS_AND_EASTERLINGS),
        l(NORTH_RHUN, listOf(EAST_RHUN, VALE_OF_THE_CARNEN, VALE_OF_THE_CELDUIN, NORTHERN_DORWINION), SOUTHRONS_AND_EASTERLINGS, VILLAGE),
        l(HARLINDON, listOf(GREY_HAVENS, SOUTH_ERED_LUIN)),
        l(SOUTH_ERED_LUIN, listOf(THE_SHIRE, TOWER_HILLS, HARLINDON, MINHIRIATH, CARDOLAN, OLD_FOREST)),
        l(OLD_FOREST, listOf(BUCKLAND, THE_SHIRE, SOUTH_ERED_LUIN, CARDOLAN)),
        l(CARDOLAN, listOf(OLD_FOREST, SOUTH_ERED_LUIN, MINHIRIATH, THARBAD, NORTH_DUNLAND, SOUTH_DOWNS, BUCKLAND)),
        l(SOUTH_DOWNS, listOf(WEATHER_HILLS, BREE, BUCKLAND, CARDOLAN, NORTH_DUNLAND, HOLLIN, TROLLSHAWS)),
        l(HOLLIN, listOf(FORDS_OF_BRUINEN, TROLLSHAWS, SOUTH_DOWNS, NORTH_DUNLAND, MORIA)),
        l(MORIA, listOf(HOLLIN, NORTH_DUNLAND, DIMRILL_DALE), SAURON, STRONGHOLD),
        l(GLADDEN_FIELDS, listOf(OLD_FORD, DIMRILL_DALE, RHOSGOBEL, NORTH_ANDUIN_VALE)),
        l(NORTH_ANDUIN_VALE, listOf(RHOSGOBEL, GLADDEN_FIELDS, DIMRILL_DALE, SOUTH_ANDUIN_VALE, DOL_GULDUR, NARROWS_OF_THE_FOREST)),
        l(NARROWS_OF_THE_FOREST, listOf(OLD_FOREST_ROAD, RHOSGOBEL, NORTH_ANDUIN_VALE, DOL_GULDUR, EASTERN_MIRKWOOD)),
        l(EASTERN_MIRKWOOD, listOf(OLD_FOREST_ROAD, NARROWS_OF_THE_FOREST, DOL_GULDUR, SOUTHERN_MIRKWOOD, NORTHERN_RHOVANION)),
        l(NORTHERN_RHOVANION, listOf(DALE, OLD_FOREST_ROAD, EASTERN_MIRKWOOD, SOUTHERN_MIRKWOOD, SOUTHERN_RHOVANION, VALE_OF_THE_CELDUIN, VALE_OF_THE_CARNEN)),
        l(VALE_OF_THE_CELDUIN, listOf(VALE_OF_THE_CARNEN, NORTHERN_RHOVANION, SOUTHERN_RHOVANION, NORTHERN_DORWINION, NORTH_RHUN)),
        l(MINHIRIATH, listOf(SOUTH_ERED_LUIN, ENEDWAITH, THARBAD, CARDOLAN)),
        l(THARBAD, listOf(CARDOLAN, MINHIRIATH, ENEDWAITH, SOUTH_DUNLAND, NORTH_DUNLAND)),
        l(NORTH_DUNLAND, listOf(MORIA, HOLLIN, SOUTH_DOWNS, CARDOLAN, THARBAD, SOUTH_DUNLAND), ISENGARD, VILLAGE),
        l(SOUTH_DUNLAND, listOf(NORTH_DUNLAND, THARBAD, ENEDWAITH, GAP_OF_ROHAN), ISENGARD, VILLAGE),
        l(LORIEN, listOf(DIMRILL_DALE, PARTH_CELEBRANT), ELVES, STRONGHOLD),
        l(PARTH_CELEBRANT, listOf(LORIEN, FANGORN, EASTEMNET, WESTERN_BROWN_LANDS, SOUTH_ANDUIN_VALE, DIMRILL_DALE)),
        l(DIMRILL_DALE, listOf(GLADDEN_FIELDS, MORIA, LORIEN, PARTH_CELEBRANT, SOUTH_ANDUIN_VALE, NORTH_ANDUIN_VALE)),
        l(SOUTH_ANDUIN_VALE, listOf(NORTH_ANDUIN_VALE, DIMRILL_DALE, PARTH_CELEBRANT, WESTERN_BROWN_LANDS, DOL_GULDUR)),
        l(
            DOL_GULDUR, listOf(NARROWS_OF_THE_FOREST, NORTH_ANDUIN_VALE, SOUTH_ANDUIN_VALE, WESTERN_BROWN_LANDS, EASTERN_BROWN_LANDS, SOUTHERN_MIRKWOOD, EASTERN_MIRKWOOD),
            SAURON, STRONGHOLD
        ),
        l(SOUTHERN_MIRKWOOD, listOf(EASTERN_MIRKWOOD, DOL_GULDUR, EASTERN_BROWN_LANDS, SOUTHERN_RHOVANION, NORTHERN_RHOVANION), SAURON),
        l(SOUTHERN_RHOVANION, listOf(NORTHERN_RHOVANION, SOUTHERN_MIRKWOOD, EASTERN_BROWN_LANDS, NOMAN_LANDS, SOUTHERN_DORWINION, NORTHERN_DORWINION, VALE_OF_THE_CELDUIN)),
        l(NORTHERN_DORWINION, listOf(VALE_OF_THE_CELDUIN, SOUTHERN_RHOVANION, SOUTHERN_DORWINION, NORTH_RHUN)),
        l(ENEDWAITH, listOf(THARBAD, MINHIRIATH, DRUWAITH_IAUR, GAP_OF_ROHAN, SOUTH_DUNLAND)),
        l(GAP_OF_ROHAN, listOf(SOUTH_DUNLAND, ENEDWAITH, DRUWAITH_IAUR, FORDS_OF_ISEN, ORTHANC), ISENGARD),
        l(ORTHANC, listOf(GAP_OF_ROHAN, FORDS_OF_ISEN), ISENGARD, STRONGHOLD),
        l(FANGORN, listOf(PARTH_CELEBRANT, FORDS_OF_ISEN, WESTEMNET, EASTEMNET)),
        l(EASTEMNET, listOf(PARTH_CELEBRANT, FANGORN, WESTEMNET, FOLDE, DRUADAN_FOREST, WESTERN_EMYN_MUIL, WESTERN_BROWN_LANDS), ROHAN),
        l(WESTERN_BROWN_LANDS, listOf(DOL_GULDUR, SOUTH_ANDUIN_VALE, PARTH_CELEBRANT, EASTEMNET, WESTERN_EMYN_MUIL, EASTERN_BROWN_LANDS)),
        l(EASTERN_BROWN_LANDS, listOf(SOUTHERN_MIRKWOOD, DOL_GULDUR, WESTERN_BROWN_LANDS, WESTERN_EMYN_MUIL, EASTERN_EMYN_MUIL, NOMAN_LANDS, SOUTHERN_RHOVANION)),
        l(NOMAN_LANDS, listOf(SOUTHERN_RHOVANION, EASTERN_BROWN_LANDS, EASTERN_EMYN_MUIL, DAGORLAD, ASH_MOUNTAINS, SOUTHERN_DORWINION)),
        l(SOUTHERN_DORWINION, listOf(NORTHERN_DORWINION, SOUTHERN_RHOVANION, NOMAN_LANDS, ASH_MOUNTAINS, SOUTH_RHUN)),
        l(SOUTH_RHUN, listOf(EAST_RHUN, SOUTHERN_DORWINION, ASH_MOUNTAINS), SOUTHRONS_AND_EASTERLINGS, VILLAGE),
        l(DRUWAITH_IAUR, listOf(ENEDWAITH, ANDRAST, FORDS_OF_ISEN, GAP_OF_ROHAN)),
        l(FORDS_OF_ISEN, listOf(ORTHANC, GAP_OF_ROHAN, DRUWAITH_IAUR, HELMS_DEEP, WESTEMNET, FANGORN), ROHAN, FORTIFICATION),
        l(WESTEMNET, listOf(FANGORN, FORDS_OF_ISEN, HELMS_DEEP, EDORAS, FOLDE, EASTEMNET), ROHAN, VILLAGE),
        l(WESTERN_EMYN_MUIL, listOf(WESTERN_BROWN_LANDS, EASTEMNET, DRUADAN_FOREST, DEAD_MARSHES, EASTERN_EMYN_MUIL, EASTERN_BROWN_LANDS)),
        l(EASTERN_EMYN_MUIL, listOf(EASTERN_BROWN_LANDS, WESTERN_EMYN_MUIL, DEAD_MARSHES, NORTH_ITHILIEN, DAGORLAD, NOMAN_LANDS)),
        l(HELMS_DEEP, listOf(FORDS_OF_ISEN, WESTEMNET), ROHAN, STRONGHOLD),
        l(EDORAS, listOf(WESTEMNET, FOLDE), ROHAN, CITY),
        l(FOLDE, listOf(EASTEMNET, WESTEMNET, EDORAS, DRUADAN_FOREST), ROHAN, VILLAGE),
        l(DRUADAN_FOREST, listOf(EASTEMNET, FOLDE, MINAS_TIRITH, OSGILIATH, DEAD_MARSHES, WESTERN_EMYN_MUIL), GONDOR),
        l(DEAD_MARSHES, listOf(EASTERN_EMYN_MUIL, WESTERN_EMYN_MUIL, DRUADAN_FOREST, OSGILIATH, NORTH_ITHILIEN)),
        l(NORTH_ITHILIEN, listOf(EASTERN_EMYN_MUIL, DEAD_MARSHES, OSGILIATH, SOUTH_ITHILIEN, MINAS_MORGUL, DAGORLAD)),
        l(DAGORLAD, listOf(NOMAN_LANDS, EASTERN_EMYN_MUIL, NORTH_ITHILIEN, MORANNON, ASH_MOUNTAINS)),
        l(ASH_MOUNTAINS, listOf(SOUTHERN_DORWINION, NOMAN_LANDS, DAGORLAD, SOUTH_RHUN)),
        l(ANDRAST, listOf(DRUWAITH_IAUR, ANFALAS)),
        l(ANFALAS, listOf(ANDRAST, ERECH, DOL_AMROTH), GONDOR),
        l(ERECH, listOf(ANFALAS, DOL_AMROTH, LAMEDON), GONDOR),
        l(DOL_AMROTH, listOf(ANFALAS, ERECH, LAMEDON), GONDOR, STRONGHOLD),
        l(LAMEDON, listOf(ERECH, DOL_AMROTH, PELARGIR), GONDOR, VILLAGE),
        l(PELARGIR, listOf(LAMEDON, WEST_HARONDOR, LOSSARNACH, OSGILIATH), GONDOR, CITY),
        l(LOSSARNACH, listOf(MINAS_TIRITH, PELARGIR, OSGILIATH), GONDOR, VILLAGE),
        l(MINAS_TIRITH, listOf(DRUADAN_FOREST, LOSSARNACH, OSGILIATH), GONDOR, STRONGHOLD),
        l(OSGILIATH, listOf(DEAD_MARSHES, DRUADAN_FOREST, MINAS_TIRITH, LOSSARNACH, PELARGIR, WEST_HARONDOR, SOUTH_ITHILIEN, NORTH_ITHILIEN), null, FORTIFICATION),
        l(SOUTH_ITHILIEN, listOf(NORTH_ITHILIEN, OSGILIATH, WEST_HARONDOR, EAST_HARONDOR, MINAS_MORGUL)),
        l(MINAS_MORGUL, listOf(NORTH_ITHILIEN, SOUTH_ITHILIEN, GORGOROTH), SAURON, STRONGHOLD),
        l(GORGOROTH, listOf(BARAD_DUR, MORANNON, MINAS_MORGUL, NURN), SAURON),
        l(MORANNON, listOf(DAGORLAD, GORGOROTH), SAURON, STRONGHOLD),
        l(BARAD_DUR, listOf(GORGOROTH), SAURON, STRONGHOLD),
        l(WEST_HARONDOR, listOf(PELARGIR, UMBAR, NEAR_HARAD, EAST_HARONDOR, SOUTH_ITHILIEN, OSGILIATH)),
        l(EAST_HARONDOR, listOf(SOUTH_ITHILIEN, WEST_HARONDOR, NEAR_HARAD)),
        l(NURN, listOf(GORGOROTH), SAURON, VILLAGE),
        l(UMBAR, listOf(WEST_HARONDOR, NEAR_HARAD), SOUTHRONS_AND_EASTERLINGS, STRONGHOLD),
        l(NEAR_HARAD, listOf(EAST_HARONDOR, WEST_HARONDOR, UMBAR, FAR_HARAD, KHAND), SOUTHRONS_AND_EASTERLINGS, VILLAGE),
        l(FAR_HARAD, listOf(KHAND, NEAR_HARAD), SOUTHRONS_AND_EASTERLINGS, CITY),
        l(KHAND, listOf(NEAR_HARAD, FAR_HARAD), SOUTHRONS_AND_EASTERLINGS)
    )

    fun newGame() = GameState(LocationName.entries.associateWith { getLocation(it) }, createReinforcements(), createCompanions())

    private fun getLocation(name: LocationName) = initLocations.first { it.name == name }

    private fun getFigures(name: LocationName, nation: NationName?): Figures {
        if (initFigures.containsKey(name)) {
            val notNullNation = initFigures[name]!!.second ?: nation!!
            val all = initFigures[name]!!.first
                .map { Figure(it, notNullNation) }
            return Figures(all)
        } else {
            return Figures(emptyList())
        }
    }

    private fun createReinforcements() = Figures(
        createFiguresFromNationName(DWARVES, 2, 3, 3) +
                createFiguresFromNationName(ELVES, 2, 4) +
                createFiguresFromNationName(GONDOR, 6, 4, 3) +
                createFiguresFromNationName(NORTHMEN, 6, 4, 3) +
                createFiguresFromNationName(ROHAN, 6, 4, 3) +
                createFiguresFromNationName(ISENGARD, 6, 5) +
                createFiguresFromNationName(SAURON, 8, 4, 4) +
                createFiguresFromNationName(SOUTHRONS_AND_EASTERLINGS, 10, 3) +
                listOf(Figure(FigureType.WITCH_KING, SAURON), Figure(FigureType.MOUTH_OF_SAURON, SAURON), Figure(FigureType.SARUMAN, ISENGARD)) +
                listOf(Figure(FigureType.ARAGORN, FREE_PEOPLE), Figure(FigureType.GANDALF_THE_WHITE, FREE_PEOPLE)),
        FiguresType.REINFORCEMENTS
    )

    private fun createCompanions() = listOf(
        Figure(FigureType.GANDALF_THE_GREY, FREE_PEOPLE),
        Figure(FigureType.STRIDER, NORTHMEN),
        Figure(FigureType.GIMLI, DWARVES),
        Figure(FigureType.LEGOLAS, ELVES),
        Figure(FigureType.BOROMIR, GONDOR),
        Figure(FigureType.PEREGRIN, FREE_PEOPLE),
        Figure(FigureType.MERIADOC, FREE_PEOPLE)
    )

    private fun l(name: LocationName, adjacent: List<LocationName>, nation: NationName? = null, type: LocationType? = null) =
        Location(name, adjacent, nation, type ?: NONE, getFigures(name, nation))

    private fun f(name: LocationName, numRegular: Int, numElite: Int, numLeaderOrNazgul: Int, nation: NationName? = null) =
        name to Pair(createFigures(numRegular, numElite, numLeaderOrNazgul), nation)

    private fun createFiguresFromNationName(nation: NationName, numRegular: Int, numElite: Int, numLeaderOrNazgul: Int = 0) =
        createFigures(numRegular, numElite, numLeaderOrNazgul)
            .map { Figure(it, nation) }

    private fun createFigures(numRegular: Int, numElite: Int, numLeaderOrNazgul: Int) = (0 until numRegular).map { FigureType.REGULAR } +
            (0 until numElite).map { FigureType.ELITE } +
            (0 until numLeaderOrNazgul).map { FigureType.LEADER_OR_NAZGUL }
}
