package ch.chrigu.wotr.location

enum class LocationName(val shortcut: String) {
    ANDRAST("and"),
    ANFALAS("anf"),
    ANGMAR("ang"),
    ARNOR("arn"),
    ASH_MOUNTAINS("am"),
    BARAD_DUR("bd"),
    BREE("br"),
    BUCKLAND("bu"),
    CARDOLAN("cn"),
    CARROCK("ck"),
    DAGORLAD("dad"),
    DALE("da"),
    DEAD_MARSHES("dm"),
    DIMRILL_DALE("dd"),
    DOL_AMROTH("dam"),
    DOL_GULDUR("dg"),
    DRUADAN_FOREST("df"),
    DRUWAITH_IAUR("di"),
    EAGLES_EYRIE("ee"),
    EAST_HARONDOR("eh"),
    EAST_RHUN("erh"),
    EASTEMNET("ea"),
    EASTERN_BROWN_LANDS("ebl"),
    EASTERN_EMYN_MUIL("eem"),
    EASTERN_MIRKWOOD("em"),
    EDORAS("ed"),
    ENEDWAITH("en"),
    EREBOR("eb"),
    ERECH("ere"),
    ERED_LUIN("el"),
    ETTENMOORS("et"),
    EVENDIM("ev"),
    FANGORN("fa"),
    FAR_HARAD("fh"),
    FOLDE("fol"),
    FORDS_OF_BRUINEN("fb"),
    FORDS_OF_ISEN("fi"),
    FORLINDON("for"),
    GAP_OF_ROHAN("gr"),
    GLADDEN_FIELDS("gf"),
    GOBLINS_GATE("gg"),
    GORGOROTH("go"),
    GREY_HAVENS("gh"),
    HARLINDON("ha"),
    HELMS_DEEP("hd"),
    HIGH_PASS("hp"),
    HOLLIN("ho"),
    IRON_HILLS("ih"),
    KHAND("kh"),
    LAMEDON("la"),
    LORIEN("lor"),
    LOSSARNACH("los"),
    MINAS_MORGUL("mm"),
    MINAS_TIRITH("mt"),
    MINHIRIATH("mi"),
    MORANNON("mn"),
    MORIA("mo"),
    MOUNT_GRAM("mgr"),
    MOUNT_GUNDABAD("mgu"),
    NARROWS_OF_THE_FOREST("nf"),
    NEAR_HARAD("nh"),
    NOMAN_LANDS("nl"),
    NORTH_ANDUIN_VALE("nav"),
    NORTH_DOWNS("nds"),
    NORTH_DUNLAND("ndd"),
    NORTH_ERED_LUIN("nel"),
    NORTH_ITHILIEN("ni"),
    NORTH_RHUN("nrh"),
    NORTHERN_DORWINION("ndn"),
    NORTHERN_MIRKWOOD("nm"),
    NORTHERN_RHOVANION("nrv"),
    NURN("nu"),
    OLD_FORD("ofd"),
    OLD_FOREST("oft"),
    OLD_FOREST_ROAD("ofr"),
    ORTHANC("or"),
    OSGILIATH("os"),
    PARTH_CELEBRANT("pc"),
    PELARGIR("pe"),
    RHOSGOBEL("rh"),
    RIVENDELL("ri"),
    SOUTH_ANDUIN_VALE("sav"),
    SOUTH_DOWNS("sdo"),
    SOUTH_DUNLAND("sdu"),
    SOUTH_ERED_LUIN("sel"),
    SOUTH_ITHILIEN("si"),
    SOUTH_RHUN("srh"),
    SOUTHERN_DORWINION("sd"),
    SOUTHERN_MIRKWOOD("sm"),
    SOUTHERN_RHOVANION("srv"),
    THARBAD("thb"),
    THE_SHIRE("sh"),
    TOWER_HILLS("th"),
    TROLLSHAWS("tr"),
    UMBAR("um"),
    VALE_OF_THE_CARNEN("vca"),
    VALE_OF_THE_CELDUIN("vce"),
    WEATHER_HILLS("whi"),
    WEST_HARONDOR("wha"),
    WESTEMNET("we"),
    WESTERN_BROWN_LANDS("wbl"),
    WESTERN_EMYN_MUIL("wem"),
    WESTERN_MIRKWOOD("wm"),
    WITHERED_HEATH("wh"),
    WOODLAND_REALM("wr");

    val fullName = name.lowercase().replace("_", " ").replaceFirstChar { it.uppercaseChar() }

    override fun toString() = fullName

    companion object {
        fun search(prefix: String) = entries.flatMap { listOf(it.fullName, it.shortcut) }
            .filter { it.startsWith(prefix, ignoreCase = true) }
            .map { it.lowercase() }

        fun get(name: String) = entries.filter { it.fullName.equals(name, true) || it.shortcut.equals(name, true) }
            .let {
                if (it.isEmpty()) throw IllegalArgumentException("Invalid location $name")
                else if (it.size > 1) throw IllegalArgumentException("Multiple matching locations for $name: ${it.joinToString(", ")}")
                else it[0]
            }
    }
}
